# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: reg-exp-derivatives
version: '0.0.1'
github: "githubuser/reg-exp-derivatives"
license: MIT
author: "Arman Jindal"
maintainer: "Arman Jindal"
# synopsis: A new Haskeleton package.
# description: reg-exp-derivatives is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  dependencies:
  - base
  - megaparsec
  - text
  - containers
  - graphviz
  source-dirs: library

executables:
  reg-exp-derivatives:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - reg-exp-derivatives
    - containers
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  reg-exp-derivatives-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - reg-exp-derivatives
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  reg-exp-derivatives-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - reg-exp-derivatives
    - hspec
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - megaparsec
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
